    version: 2
    jobs:
        one:
            docker:
                - image: circleci/postgres:9.6-alpine-ram
            steps:
                - run: sleep(60) && echo 2
        two:
            docker:
                - image: circleci/ruby:2.4
            steps:
                - run: sleep(60) && echo 2
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
 