    version: 2
    jobs:
        one:
            docker:
                - image: circleci/ruby:2.4
                - image: circleci/postgres:9.6-alpine-ram
                  environment:
                    POSTGRES_USER: postgres
            steps:
                - run:
                    name: Installing Dependencies
                    command: |
                      sudo apt-get install postgresql-client

                - run:
                    name: Running Test
                    command: |
                      psql -h localhost -p 5432 -U postgres -c "create database test"
        two:
            docker:
                - image: circleci/ruby:2.4
            steps:
                - run: echo 2
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
 