    version: 2
    jobs:
        one:
          docker:
                - image: circleci/postgres:9.6-alpine-ram
          steps:
              run:
                  command: |
                      set +e
                      set +o pipefail
                      psql -h localhost -p 5432 -d circleci -c 'CREATE ROLE mnr'
        two:
          docker:
                - image: circleci/ruby:2.4
          steps:
            - run: sleep(60) && echo 2
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
 