    version: 2
    jobs:
        one:
            docker:
                - image: circleci/postgres:9.6-alpine-ram
                  environment:
                    POSTGRES_DB: circleci
                    POSTGRES_USER: circleci
                    POSTGRES_PASSWORD: circleci
            steps:
                - run: psql -h localhost -p 5432 -d circleci -c 'CREATE ROLE mnr'
        two:
            docker:
                - image: circleci/ruby:2.4
            steps:
                - run: echo 2
    
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
 