    version: 2
    jobs:
        one:
            docker:
                - image: circleci/ruby:2.4
                - image: circleci/postgres:9.6-alpine-ram
                  environment:
                    POSTGRES_USER: postgres
            steps:
                - run:
                    name: Wait for db
                    command: dockerize -wait tcp://localhost:5432 -timeout 1m

                - run:
                    name: Installing Dependencies
                    command: |
                      sudo apt-get install postgresql-client

                - run:
                    name: Running Test One
                    command: |
                      psql -h localhost -p 5432 -U postgres -c "create database test"
                      psql -h localhost -p 5432 -U postgres -c "CREATE TABLE one (foo VARCHAR(50));"
                      psql -h localhost -p 5432 -U postgres -c "insert into foo (\'one\');"
                      psql -h localhost -p 5432 -U postgres -c "select * from foo;"

        two:
            docker:
                - image: circleci/ruby:2.4
                - image: circleci/postgres:9.6-alpine-ram
                  environment:
                    POSTGRES_USER: postgres
            steps:
                - run:
                    name: Wait for db
                    command: dockerize -wait tcp://localhost:5432 -timeout 1m

                - run:
                    name: Installing Dependencies
                    command: |
                      sudo apt-get install postgresql-client

                - run:
                    name: Running Test Two
                    command: |
                      psql -h localhost -p 5432 -U postgres -c "create database test"
                      psql -h localhost -p 5432 -U postgres -c "CREATE TABLE two (foo VARCHAR(50));"
                      psql -h localhost -p 5432 -U postgres -c "insert into foo (\'two\');"
                      psql -h localhost -p 5432 -U postgres -c "select * from foo;"
   
    workflows:
        version: 2
        build:
            jobs:
                - one
                - two
 